apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redisinsight.fullname" . }}-pv-claim
  labels:
    app: {{ include "redisinsight.fullname" . }}
spec:
  accessModes: {{ toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
