apiVersion: v1
kind: Service
metadata:
  name: {{ include "redisinsight.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "redisinsight.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
